trigger:
- main
pool:
  name: 'Default'
stages:
- stage: Deploy
  jobs:
  - job: DeployAKS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure-Demo'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Deploy AKS using Bicep
          az deployment group create \
          --resource-group AKS-RG \
          --template-file aks-cluster.bicep \
          --parameters @parameters.json 
    displayName: 'Deploy AKS Cluster using Bicep new'
