trigger:
- main
#variables:
 # clientSecret : '$(secret.clisecret)'
  #clientId : 'e83b465b-5419-495d-b029-993bba2c6636r'
  #tenantId : '438ec686-85a2-42e0-9a71-0bfc236adee6'
  #subscriptionId : '22ebdf17-ad01-4f71-a895-cb078a581d15'
  #dnsZoneName : 'azureexternalnew.com'
  #dnsZoneResourceGroup : 'DNS_ZONE_RG'
  
pool:
  name: 'Default'
stages:
- stage: Deploy
  jobs:
  - job: DeployAKS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure-Demo'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Deploy AKS using Bicep
          az deployment group create \
          --resource-group AKS-DNS \
          --template-file aks-cluster.bicep \
          --parameters @parameters.json
          # Get AKS credentials
    displayName: 'Deploy AKS Cluster using Bicep new'
